In [17]:
import pandas as pd
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [16]:
df = pd.read_csv("data.csv")
df.rename(columns=lambda x: x[0].lower() + x.strip().lower().replace(' ', '_')[1:], inplace=True)
df = df.convert_dtypes()
df

     2025_rank  2024_rank                              institution_name  \n0            1          1  Massachusetts Institute of Technology (MIT)
1            2          6                       Imperial College London
2            3          3                          University of Oxford
3            4          4                            Harvard University
4            5          2                       University of Cambridge
...        ...        ...                                           ...
1498     1401+  1201-1400               University of Montana Missoula
1499     1401+      1401+                          University of Oradea
1500     1401+  1201-1400                      University of San Carlos
1501     1401+      1401+      University Politehnica of Timisoara, UPT
1502     1401+      1401+                 Western Washington University

     location   location_full size  academic_reputation  employer_reputation  \n0          US   United States    M                100.0                100.0
1          UK  United Kingdom    L                 98.5                 99.5
2          UK  United Kingdom    L                100.0                100.0
3          US   United States    L                100.0                100.0
4          UK  United Kingdom    L                100.0                100.0
...       ...             ...  ...                  ...                  ...
1498       US   United States    M                  3.0                  2.2
1499       RO         Romania    L                  5.6                  2.2
1500       PH     Philippines    M                  7.2                  9.4
1501       RO         Romania    L                  4.1                  4.2
1502       US   United States    L                  2.6                  2.6

      faculty_student  citations_per_faculty  international_faculty  \n0               100.0                  100.0                   99.3
1                98.2                   93.9                  100.0
2               100.0                   84.8                   98.1
3                96.3                  100.0                   74.1
4               100.0                   84.6                  100.0
...               ...                    ...                    ...
1498             10.6                    6.1                    1.3
1499              4.0                    1.9                    1.5
1500              3.3                    1.8                    2.1
1501              7.2                    3.9                    1.4
1502              7.3                    3.5                    9.7

      international_students  international_research_network  \n0                       86.8                            96.0
1                       99.6                            97.4
2                       97.7                           100.0
3                       69.0                            99.6
4                       94.8                            99.3
...                      ...                             ...
1498                     1.9                             6.5
1499                     5.2                            34.5
1500                     2.1                             6.4
1501                     2.5                            18.6
1502                     1.6                            12.4

      employment_outcomes  sustainability qs_overall_score
0                   100.0            99.0              100
1                    93.4            99.7             98.5
2                   100.0            85.0             96.9
3                   100.0            84.4             96.8
4                   100.0            84.8             96.7
...                   ...             ...              ...
1498                  3.1             1.0                -
1499                  6.2             2.3                -
1500                  9.6             1.0                -
1501                  3.9             1.1                -
1502                  1.5             1.1                -

[1503 rows x 16 columns]